apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-otel.fullname" . | default "hello-otel" }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
